### ISSUE TITLE
Request: Keep "stable" branch in sync with releases for easy updating?

### ISSUE THREAD

**Issue by smiley** [Elundris/Air-for-Steam#11]
Since this skin is on Github, I'd prefer to use git to keep it updated rather than redownload it, but I don't want to update to some potentially unstable point in development. Can you have another branch called `stable` which is merged from `master` when you release a new version? That way I (and other users familiar with git) can checkout `stable` and pull it daily, always having the latest release (and not the latest in-development version).

**Comment by Elundris** [comment]
Master is actually my stable branch. I do all new tweaks on the develop branch and only merge back to master for stable releases.
