### ISSUE TITLE
Websites in the overlay browser are cut off at the bottom

### ISSUE THREAD

**Issue by BarclayTech** [Elundris/Air-for-Steam#13]
There seems to be a bit of a scaling issue or something.

As not the whole website is displayed, the buttom of the site is cut off as it thinks the box is bigger than it is, it shows on websites like Soundcloud, if you play a song, you can only see half of the bottom bar used to play / pause / change volume / song position.

**Comment by sebie** [comment]
First of all, I get what you are talking about, as I use SoundCloud.

But, I will have to ask you a few qustions;

1. Can you confirm that you have the latest version of Air-for-Steam?
2. Does it occour in the overlay or in a 'windowed' tab?
3. If you wouldn't mind taking a screenshot, that would be great.

Thank you!

**Comment by BarclayTech** [comment]
1. I'm using the latest development version for the official dark theme. 
2. It occurs in the overlay when the browser is open
3. Done
![untitled](https://cloud.githubusercontent.com/assets/1431358/7127232/f0598390-e238-11e4-8c07-63510fe69b62.png)

It's not JUST Soundcloud it happens to, it's just the best example I can give. I've tested other skins to see if it was an issue my-end but all others work fine. It's noticeable on any website with a "Bottom bar" e.g faceit.com, etc.

**Comment by Elundris** [comment]
Looking into it, thanks for the screenshot.

**Comment by Elundris** [comment]
Should be fixed in develop.
