### ISSUE TITLE
Screenshot uploader layout issues

### ISSUE THREAD

**Issue by vincent-t** [Elundris/Air-for-Steam#18]
This bug also occures with the default theme, maybe you can fix it:
![bug](https://cloud.githubusercontent.com/assets/959709/7215062/197d1742-e5c6-11e4-82d4-ae6b701c42ef.png)

best regards

vincent

**Comment by sebie** [comment]
Thanks for reporting the bug, I just have some additional questions for you;

1. Reporting it on Linux, correct?
2. Have you installed the required fonts for Air?
3. When you said "it occurs on the default theme", do you mean that it happens on a non-skinned version of Steam or the default Air?

Cheers,

**Comment by Elundris** [comment]
Yeah, this'll be a layout related bug, not fonts.

Interesting that it happens on vanilla Steam as well, I wonder what they did. I'd also be curious if it works in Pressure skin. DD has been pretty aggressive about fixing OSX and Linux bugs.

**Comment by sebie** [comment]
Just wondering, if we fix it; it might be better if you report it to <ValveSoftware/Steam-for-Linux>.

**Comment by Mocha-Bean** [comment]
![](http://i.imgur.com/IGFxUPA.png)

I'm also on Linux; I'm not having that issue. I just tried it for the sake of testing.

**Comment by Elundris** [comment]
My guess is that there was a Linux bug with the default skin that Valve has since fixed. Closing for now, please re-open if it becomes an issue again.
