### ISSUE TITLE
Steam Overlay Chat Text

### ISSUE THREAD

**Issue by averagecomputerguy** [Elundris/Air-for-Steam#19]
![](http://puu.sh/hjyL7/3ee7ccf649.jpg)

Currently whenever I use the steam overlay in any of my games the text on the friends list and chat window looks more blocky. Typically it's unpleasant to read.

* Same outcome in stable steam client and beta
* Windows 7

**Comment by Elundris** [comment]
Sadly this is not something that I can fix in the light theme. It's a Steam text rendering bug that only occurs with dark text on light background.

Using a dark theme is really the only workaround and I may conditionally have the light theme overlay use dark colors when the dark theme releases.
