### ISSUE TITLE
Missing Music Library Skin in Overlay

### ISSUE THREAD

**Issue by axxxrey** [Elundris/Air-for-Steam#21]
While in Steam Overlay, there's no skin for the music library, or at least it seems to be broken.
* Not a beta client tester,
* Win8.1.

![ss 2015-04-22 at 09 11 28](https://cloud.githubusercontent.com/assets/8601692/7283659/5af4169c-e938-11e4-992c-3dad930e88e9.jpg)

**Comment by Elundris** [comment]
Closing as fixed in develop.
