### ISSUE TITLE
An idea to fix the circles around avatars on main window

### ISSUE THREAD

**Issue by 1112e** [Elundris/Air-for-Steam#27]
new
![2015-05-10_08-20-31](https://cloud.githubusercontent.com/assets/5818067/7554896/000be246-f6ee-11e4-8e8e-c71e6672604a.png)

old
![2015-05-10_08-26-03](https://cloud.githubusercontent.com/assets/5818067/7554914/59034aba-f6ee-11e4-91ce-80a66fdc29a0.png)

My idea is to have each area (achievements, friends, dlc, news) on its own "card"

**Comment by 1112e** [comment]
![steam_2015-05-10_11-09-43](https://cloud.githubusercontent.com/assets/5818067/7555619/cd84fe8a-f705-11e4-850f-c34f042bd8dc.png)

Better yet, the colors can be swapped as seen here

**Comment by Elundris** [comment]
I'll keep this open for now, as it may come in handy in the future.

For now, the main reason I was avoiding swapping colors was to keep consistency throughout the skin. All list panels use the same bg color and I didn't want to swap it here on the details page only.
