### ISSUE TITLE
Dot points in releases?

### ISSUE THREAD

**Issue by sebie** [Elundris/Air-for-Steam#28]
I modified the change list in the [latest](https://github.com/Elundris/Air-for-Steam/releases/tag/2015-0510) to have dot points before it.

Can I apply this to the other releases or undo it?

**Comment by Elundris** [comment]
Go for it, I just kept the formatting from ages ago so there wasn't much thought behind bullets vs no bullets. :)

**Comment by sebie** [comment]
Ok, thanks. Going to do that :ok_hand:
