### ISSUE TITLE
Missing Text in Drop-Down Menus

### ISSUE THREAD

**Issue by tadev** [Elundris/Air-for-Steam#29]
Theres no text in any of the Drop-Down Menus.
Even on the Systray of steam.
Also, i see no notification icon.

OS: Windows 7 x64, Steam version release.

Version is latest Master. https://github.com/Elundris/Air-for-Steam/commit/7bf10d218a6ed98e6317abc594b25ebfe0776cef

http://i.imgur.com/jyxYIIK.png
http://i.imgur.com/pcQ68Rj.png

Customizations to Skin: Enabled Dark Theme in config.ini, enabled Numix Color-Palette in config.ini

**Comment by Elundris** [comment]
Can you confirm that you've installed the Roboto Medium font?

The notification icon will only appear when you have unread messages.

**Comment by tadev** [comment]
Nevermind i am stupid. I had the fonts installed but apparently some of them were corrupt. I overwrote them with the fonts in the package. It works now.
