### ISSUE TITLE
Notification icon missing(?) when there's no notification on the latest version (Top right)

### ISSUE THREAD

**Issue by Sphincone** [Elundris/Air-for-Steam#32]
It's happening for both themes. Well when I have no notification, shouldn't the Flag dim? Or else it seems like something is missing when I have no notifications. Maybe you can set the flag icon's opacity a bit low when there's no Notification. That way, there won't be anything missing :) Also most of the time most of us doesn't have any notifications (Even if we do, it gets seen immediately). 

Light when I have no notification: http://i.imgur.com/EyswJFY.png
Light when I have notifications: http://i.imgur.com/kZzB1ZT.png

Dark when I have no notification: http://i.imgur.com/B5nRAIC.png
Dark when I have notifications: http://i.imgur.com/40Uk2Sx.png

So can I do it somehow my editing the tga files? If yes, then which file should I look for, haven't dug around steam skin files.

**Comment by Sphincone** [comment]
inbox_button {
			textcolor=none
			render_bg { }
		}

		inbox_button_active {
			textcolor=none
			render_bg {
				2="image( x0 + 9, y0 + 8, x1, y1, graphics/onfocus/inbox )"
			}
		}


So I just found this piece. Can't really just simply add a image since it's not using the image, using outline of the flag image. So...help? :smiley:

**Comment by Elundris** [comment]
No worries. This was by design... though I am planning on adding an "empty" icon to the next release instead of making it disappear.

**Comment by sebie** [comment]
Fixed in latest :tada: 

`* Inbox button now has an inactive state and no longer disappears`
