### ISSUE TITLE
Notification icon is not showing up when steam uses Canadian dollar symbol

### ISSUE THREAD

**Issue by a-burman** [Elundris/Air-for-Steam#34]
Notification icon is not showing up when steam uses Canadian dollar symbol to display the wallet balance but you can still click where the notification icon should be.

![nonotification1](https://cloud.githubusercontent.com/assets/9065010/7600448/f5a77166-f8bf-11e4-8529-302091b64903.JPG)

![nonotification2](https://cloud.githubusercontent.com/assets/9065010/7600454/02a8066e-f8c0-11e4-9be7-100351222aa0.png)

**Comment by Elundris** [comment]
This was by design, the notification icon only shows up when you have unread messages. I'm updating this to use a faded icon instead.
