### ISSUE TITLE
Console tab not shown

### ISSUE THREAD

**Issue by galeksandrp** [Elundris/Air-for-Steam#35]
![image](https://cloud.githubusercontent.com/assets/3586205/7611676/9b0cedce-f98e-11e4-99e2-34e7afdc965d.png)

In Air Classic it shows as expected.

Checked on Windows 7 (64bit) at Steam (buided Apr 13 2015 15:19:29 Steam API: v017 ver 1428965940) and Steam Beta (buided May 11 2015 13:49:59 Steam API: v017 ver 1431464814)

**Comment by Elundris** [comment]
This was a purposeful change since most users will not have developer mode enabled and I was (personally) tired of seeing the tab since I run in dev mode all the time.

I usually access the console from the quick launch menu on Windows 7/8 when needed.
