### ISSUE TITLE
Downloads Completed 

### ISSUE THREAD

**Issue by victorND** [Elundris/Air-for-Steam#36]
item download complete shows on main library window, it doesn't dissapear until you click on close
![bug](https://cloud.githubusercontent.com/assets/12437132/7623624/bbff3bce-f991-11e4-9895-8a67c77d507d.jpg)

i don't know if its a personal issue, also isn't like a big deal but maybe a little something to get closer to perfection :) 

best regards.

**Comment by sebie** [comment]
I (think, I) understand what you are saying, but would mind taking a screenshot of the full thing?

Thanks.

**Comment by Elundris** [comment]
That's default Steam functionality that I have no control over. If you recall from default Steam, they have this notification on the bottom tray area and it sticks around in case Steam downloaded something when you were away (that way you are alerted when you get back).

**Comment by sebie** [comment]
Urgh, sorry. I will stick to asking general questions. ._,
