### ISSUE TITLE
Why tabs and not spaces?

### ISSUE THREAD

**Issue by robertbaker** [Elundris/Air-for-Steam#40]
It seems backwards to me, should be spaces in my opinion.

**Comment by sebie** [comment]
Would you mind taking a screenshot and mentioning your sysem specifications?

Thank you.

**Comment by Elundris** [comment]
It's just what I'm used to from HTML/CSS, feels like a cleaner maneuver to me personally.

**Comment by robertbaker** [comment]
Lots of reasons to use spaces over tabs, several great answers on SO
