### ISSUE TITLE
use material icons

### ISSUE THREAD

**Issue by robertbaker** [Elundris/Air-for-Steam#41]
https://google.github.io/material-design-icons/
notifications none 
notifications off 
notifications on 

instead of the flag

**Comment by Elundris** [comment]
This was just a personal preference of mine... I'm not a huge fan of the bell icon honestly. And even less of the one they are starting to implement these days (the small bell in the white circle).

**Comment by Elundris** [comment]
Oh, and the flag icon is material, though I'm not sure what it's actually supposed to be used for. It does seem to work well enough for a "look at me" icon though.
