### ISSUE TITLE
Can't select folders in Steam Libray Folders menu

### ISSUE THREAD

**Issue by kTron2g** [Elundris/Air-for-Steam#44]
When I'm using the air-for-steam skin, I am not able to see the folders highlighted in the Steam Library Folders Menu. I'm not sure if this is just a visual bug, or if not being able to select a specific folder is a separate bug. Without being able to see which folder is highlighted, or which folder is selected, you are not able to remove the folder you are trying to remove.

When switching back to default skin, the problem disappears.

**Comment by sebie** [comment]
Just to be sure, have you:

* Installed the fonts needed for `Air for Steam`?
* Did you restart Steam?

Otherwise would you mind taking a screenshot of it and metioning your system specifications?

Thanks!

**Comment by kTron2g** [comment]
Screenshot of the fonts installed - https://imgur.com/a/bpo5h

I didn't think I could capture the problem in a way that made sense with only a screenshot, so I took a video. I don't have any screen capture software installed, so I just used my cell-phone.

working on default skin - https://vid.me/exxf

not working on air for steam - https://vid.me/3DDM

**Comment by Elundris** [comment]
Yeah, it's just a visual bug. The selection color is simply the same color as the background, so you can remove folders, you just have to be sure you know what you clicked on.

I'll get this patched up though, nice find!

**Comment by kTron2g** [comment]
Thank you for explaining it, this skin is awesome.

If I see anything else, I'll be sure to post on here.

Thank you, and have a good night.

**Comment by Elundris** [comment]
Patched this up in the develop branch.
