### ISSUE TITLE
Some text is barely readable on dark theme with gunmetal colors

### ISSUE THREAD

**Issue by 1112e** [Elundris/Air-for-Steam#45]
![](http://i.imgur.com/DteyAXM.png)

**Comment by sebie** [comment]
I would assume that you are suggesting the `Delete` and `Cancel` buttons to be the same or atleast a similiar color to the text above it?

**Comment by Elundris** [comment]
Aware of the issue and I'll be working on separating out the background and font colors for the themes.

**Comment by sebie** [comment]
Fixed in the latest release, right? (#48 )

**Comment by 1112e** [comment]
That only fixes some text, not what was pictured

**Comment by Elundris** [comment]
I haven't had a chance to work on this yet, yesterday's update was mostly to get the changes in the develop branch out to the public since they had been sitting there for awhile. This is still on my radar, just a bit busy atm!

**Comment by Elundris** [comment]
Should be better on develop now!
