### ISSUE TITLE
Different colors for online and in game

### ISSUE THREAD

**Issue by 1112e** [Elundris/Air-for-Steam#46]
Friends.Online					"84 162 234 255"			        //friend online text
		Friends.InGame				"113 162 0 255"		        	//friend in-game text
   

Figured this was easier then doing a full pull request. 
I couldn't find where to change the colors for the overlay friends list 

Original:
![2015-05-16_21-23-38](https://cloud.githubusercontent.com/assets/5818067/7669082/7d75d428-fc14-11e4-93f4-3481961c6771.png)

New: 
![2015-05-16_21-21-24](https://cloud.githubusercontent.com/assets/5818067/7669083/82be75de-fc14-11e4-83f1-ce543bb5ceff.png)

**Comment by Elundris** [comment]
You'll have to update the override colors in gameoverlay.styles. I had to duplicate all the dark theme color values in here in order to make the overlay use the dark theme regardless.
