### ISSUE TITLE
"Write Review" cut off when scrolled to top in library.

### ISSUE THREAD

**Issue by Mocha-Bean** [Elundris/Air-for-Steam#49]
Scrolled to top:

![](http://i.imgur.com/jRzV665.png)

Scrolled down:

![](http://i.imgur.com/Zi1YkEY.png)

System info [from screenfetch]: (Reply if you need more info.)
```
  OS: Arch Linux 
  Kernel: x86_64 Linux 4.0.5-1-ARCH
  Packages: 1279
  Shell: bash 4.3.39
  Resolution: 1920x1080
  DE: XFCE4
  WM: Xfwm4
  WM Theme: Numix
  GTK Theme: Numix [GTK2], Not Found [GTK3]
  Icon Theme: Numix-Circle
  Font: Roboto 10
  CPU: Intel Core i7-3610QM CPU @ 3.3GHz
  GPU: GeForce GTX 660M
  RAM: 2716MB / 16005MB
```

**Comment by sebie** [comment]
Thanks for reporting this bug. Props for the screenshots!

(I thought I commented and tagged this, the day you reported it). 

Anyhow, thanks for reporting it. /cc: @Elundris

**Comment by Elundris** [comment]
Just to confirm, does this happen still on the most recent build (master or develop)?

How does the links section scroll? Can you scroll it by itself or does it appear to be attached to the scrolling of the main page?

**Comment by Mocha-Bean** [comment]
I do not have the issue anymore in version 2015-0616. I had the issues in 2015-0510.

Here's a screenshot of 2015-0616: http://i.imgur.com/Lv49CrC.png

I have some other issues that persist, but those are seperate so I will post them as another issue.

**Comment by Elundris** [comment]
Awesome, a cool side-effect of some other changes I was making to the details page!
