### ISSUE TITLE
Can't save game categories?

### ISSUE THREAD

**Issue by joshery420** [Elundris/Air-for-Steam#53]
To be clear, I'm referring to the menu when you right-click on a game in your library and choose "Set Categories..."
Although I can change and create categories, there doesn't appear to be a way to save our per-game category settings. Not sure if it's a resolution issue or just a button that slipped through the cracks, but I don't see any sort of save/OK button being rendered.
Running the latest Steam client version (June 2nd, 2015 update) and latest Air-for-Steam skin version (2015-0616, dark Cinnabar theme)

**Comment by sebie** [comment]
Just checking, does it work on the default theme?

**Comment by joshery420** [comment]
mhmm. I had to switch back to the default Steam skin in order to set some categories earlier and it works just fine.

**Comment by Elundris** [comment]
Is this what you are talking about?

![categories](https://cloud.githubusercontent.com/assets/8676168/8299382/83eb8c5a-192c-11e5-90eb-85253da3991b.png)

**Comment by joshery420** [comment]
So.
You know those things where you feel really stupid?
This is one of those.
They were showing up, but they were overlaying similar looking space on the steam client.
So it didn't look like they existed as part of the dialog.
Don't mind me guys. I'm just bad at using my eyes apparently. ;)

**Comment by Elundris** [comment]
Hehe, no worries mate! :)
