### ISSUE TITLE
3 Line Friend List Directions Not Working

### ISSUE THREAD

**Issue by CampAsAChamp** [Elundris/Air-for-Steam#55]
Hey man, I was trying to test out some of the customization options on your skin, and it looks like the last option of setting the friendlist to have 3 lines no longer works. 

One of the lines seems to have been bundled in with another. I am no coder or anything, or if I'm even doing this right, but the 3 line friendslists doesn't seem to be working for me. I suspect that this might be the reason, I don't know though.
![air for steam bug](https://cloud.githubusercontent.com/assets/13057262/8368651/d9361dc4-1b61-11e5-9c12-5513b056e0ec.PNG)

**Comment by Elundris** [comment]
Essentially, what you need to do is to make your code on the right look like the code from the FAQ. From ClanStatusImage down to ControlPanelLink you can essentially do a copy/paste.

Feel free to re-open this topic if you can't get it working!
