### ISSUE TITLE
Horrible white circles around avatars in dark skin

### ISSUE THREAD

**Issue by xPaw** [Elundris/Air-for-Steam#57]
Is this intended? They also look cropped and really ugly in notifications.
![2015-06-29_00-10-26](https://cloud.githubusercontent.com/assets/613331/8398348/422e7568-1df3-11e5-8b43-860702fffa03.png)

**Comment by Elundris** [comment]
You need to make sure to copy the +Extras folder dark theme content as well: https://github.com/Elundris/Air-for-Steam/wiki#themes

**Comment by xPaw** [comment]
Whoops, my bad! Perhaps this could be mentioned in config.ini?

**Comment by sebie** [comment]
Something like a mention to the Wiki article?

**Comment by xPaw** [comment]
Well ideally it would say about +Extras folder, and link to wiki for more information if needed

**Comment by sebie** [comment]
Will make a PR either today or tomorrow and mention you to see if it makes sense. Deal?

**Comment by Elundris** [comment]
Good idea!

de7f95dae4fe4bf4e568a130dd3b7cfda5c370ee

**Comment by sebie** [comment]
:tada: :clap:
