### ISSUE TITLE
Attemtping to use the server auto-join function will crash the overlay/steam

### ISSUE THREAD

**Issue by Dmck2b** [Elundris/Air-for-Steam#58]
If using the server menu on desktop and you try to auto-join a server, steam will outright crash. Doing this in the overlay is limited to the overlay itself crashing, but it reloads itself after a few moments.

Currently running the latest comment ( https://github.com/Elundris/Air-for-Steam/commit/de7f95dae4fe4bf4e568a130dd3b7cfda5c370ee ) unedited from the repo and was previously running 616 with a few personal tweaks and the issue is prevalent in both versions.

Video of the occurrence - http://i.suddenly.coffee/2015-07-02_23-15-28.mp4

**Comment by Elundris** [comment]
2 questions:

* Does this happen with all full servers/games you try to join?
* Does this occur on the default skin as well?

**Comment by Dmck2b** [comment]
Using CS:GO as another testing game, it appears so. (Not that many games
with full servers that I can see right now)

No, only Air - http://i.suddenly.coffee/2015-07-03_10-27-55.mp4

**Comment by Elundris** [comment]
This should now be fixed on develop, was missing a layout file which was causing the crash. Good catch, and thanks for the report!

Please re-open if you are still having the issue.

**Comment by Dmck2b** [comment]
Working great, cheers for the swift fix :)
