### ISSUE TITLE
Add more notification popups at once

### ISSUE THREAD

**Issue by 1112e** [Elundris/Air-for-Steam#59]
For some reason this skin only allows 1 at a time, where the default is 3. It's annoying when I start steam, i have notifications for about 40 seconds

**Comment by MikeStardust** [comment]
Hello there, there is actually a solution for that in the [FAQ's](https://github.com/Elundris/Air-for-Steam/wiki#change-notification-stack-count)

All you have to do is browse to to your steam folder and open the following file:
```
 \Steam\skins\Air-for-Steam\Resource\styles\steam.styles
```
After that just change this value: 
```
Notifications.StackSize    "1"
```
to the number of notifications you would like to see stacked

Save the modified file and restart steam, 
Cheers.

**Comment by 1112e** [comment]
Ah, thanks!

**Comment by sebie** [comment]
Asuming all went well; please reopen if you have any additional questions! :smile:
