### ISSUE TITLE
Downloads page messed up after steam update. 

### ISSUE THREAD

**Issue by 1112e** [Elundris/Air-for-Steam#61]
![](http://i.imgur.com/BnN30Y5.png)

They added a disk activity indicator

**Comment by sebie** [comment]
I noticed this as well. Pretty sure @Elundris has a lot on his hands right now (?).  However, looking at what DD did to [Pressure](https://github.com/DirtDiglett/Pressure-for-Steam/commit/c2fc10c464a5393538d8f5bfa2ee70cb9dd27264) it seems that all that was (majorly) changed was the `DiscGraphPanel` and `DiskLegendPanel`. Right?

**Comment by djwetbeatz** [comment]
Hey guys, I noticed this issue today too and took it upon myself to try and resolve it. I've put in a pull request if anyone wants to check it out. Here's what it looks like after I applied my changes:

![downloads](https://cloud.githubusercontent.com/assets/11904616/8558073/b6f16a6c-24b6-11e5-8699-1fd8144ffc9d.png)

![downloads1](https://cloud.githubusercontent.com/assets/11904616/8558241/ae3c2fdc-24b7-11e5-8ec8-456d1caf9dd8.png)

Hopefully @Elundris sees this. Unless he's already fixed the problem, in which case, even better.

**Comment by 1112e** [comment]
Thanks!

**Comment by sebie** [comment]
Great stuff! Just need to wait for @Elundris to approve #62 and we are set. :+1:

**Comment by Elundris** [comment]
Merged #62. Will be making a few tweaks and then releasing a beta. Thanks guys!

**Comment by sebie** [comment]
Awesome. Mentioning it [here](http://steamcommunity.com/groups/airforsteam/discussions/1/537402115074699755/).
