### ISSUE TITLE
recent steam updates mess up how one would view the download usage.

### ISSUE THREAD

**Issue by innogene** [Elundris/Air-for-Steam#64]
![2015-07-08_18-35-45](https://cloud.githubusercontent.com/assets/12711938/8584911/4ad36268-25a1-11e5-81ef-f3fc08f21c3f.png)

**Comment by djwetbeatz** [comment]
This issue has already been addressed in #61 and I've made a pull request #62. You can check the file edits in #62 and make the changes manually if you like. So I'm just going to mark this as closed.

**Comment by djwetbeatz** [comment]
At this point we're just waiting on @Elundris to merge the changes or do whatever he sees fit for a fix. But in the meantime this seems to be a working solution as far as I know.

**Comment by sebie** [comment]
Created a tag for future issues like these; duplicate.
