### ISSUE TITLE
Steam Blue skin has some hard to read colors

### ISSUE THREAD

**Issue by xPaw** [Elundris/Air-for-Steam#65]
![2015-07-09_12-18-24](https://cloud.githubusercontent.com/assets/613331/8591987/9fa12346-2634-11e5-94f3-abcbc091c5a4.png)

Hover text in menus and "Achievements" title.

**Comment by sebie** [comment]
Thanks for the report @xPaw . @Elundris seemed to have pushed some updates ~3 hours ago; so he might see this and put it in the current beta.

**Comment by Elundris** [comment]
I'll see what I can do, hang tight.

**Comment by Elundris** [comment]
Re-open if this is still an issue on the develop branch. Closing.
