### ISSUE TITLE
Icons in friend list are not positioned correctly

### ISSUE THREAD

**Issue by xPaw** [Elundris/Air-for-Steam#68]
![2015-07-16_18-41-41](https://cloud.githubusercontent.com/assets/613331/8727802/5ee64334-2bea-11e5-927f-ae8c00a370a5.png)

It's either because they're in game, or big picture icon is not aligned correctly.

--

They can be seen in chat window too:
![2015-07-16_18-42-54](https://cloud.githubusercontent.com/assets/613331/8727823/80d8a7de-2bea-11e5-8db7-b4c03b7ef518.png)

**Comment by Elundris** [comment]
Tracked down the issue, thanks for the detailed report! Should be good to go on the develop branch.
