### ISSUE TITLE
[SteamGroup] "<'GridView.DropShadowLeading 7'> causes improper Grid Image scaling."

### ISSUE THREAD

**Issue by sebie** [Elundris/Air-for-Steam#70]
This is a transcript of a [issue](http://steamcommunity.com/groups/airforsteam/discussions/1/541906348037360913/) submitted to the SteamGroup. I transcribed it here, for when it gets fixed, the issue can be mentioned by it's `#`.

Original reporter: "[BONKERS](http://steamcommunity.com/id/Vosse)"

-----

Backstory:

> After being a fond user of AirClassic for a long time now, I thought i'd give the regular version a try again to see how it has come along ... I actually ended up liking it a lot now that I can make it work to my liking.

> However there is one BIG problem with Grid view (which I use almost exclusively).
Grid images aren't being scaled properly 1:1 to the original image (460x215) at max size.

> At first I thought it was just my mind playing tricks on me. But to be sure, I decided to compare between Air classic and New Air. 

> Matching the two pixel for pixel on horizontal position reveals the sizes are different. And that New Air was adding an extra 6 pixels of width for starters. (I measured this with them aligned, overlaying a grid with a line for each pixel and counted the difference).

-----

> Eventually I found that setting "GridView.DropShadowLeading" to "7" was the problem. And after setting it to `0` and the problem is solved.

Some comparisons: [Before](http://screenshotcomparison.com/comparison/135286) and [After](http://screenshotcomparison.com/comparison/135289).

**Comment by Elundris** [comment]
This property is adding a drop shadow behind all the grid images. I don't plan on removing it.
