### ISSUE TITLE
Friendslist has a too high minimum height.

### ISSUE THREAD

**Issue by Noujin** [Elundris/Air-for-Steam#71]
Hey guys. I am using Air for Steam for a really long time now but I used an older version. Having updated I saw you're using a high minimum height on the friends window layout now. I asked myself whether it has to be there because of a bug of some sort? I disabled it and it allowed me my normal desktop layout again. I just thought it may concern someone else too. 

[...]\Steam\skins\Air-for-Steam-2015-0727\Resource\styles\_layout.styles
line 76.

Thank you for the hard work on Air for Steam :)

**Comment by Elundris** [comment]
Fair enough, I just thought it looked odd that small, but alas!

It's updated on develop and will roll out live in the next update.
