### ISSUE TITLE
Roboto Font Not Loading

### ISSUE THREAD

**Issue by SoundwaveL** [Elundris/Air-for-Steam#72]
A brief description of the issue and steps to reproduce
Air Skin Doesn't load roboto font, to reproduce; Install Air Skin and Roboto, Run Steam
A screenshot (pictures are worth a million words)
http://imgur.com/a/VOS76#0
Are you opted in to the Steam Client beta?
No
Your operating system
OS X Yosemite Version 10.10.4 (14E46)

**Comment by Elundris** [comment]
Can you try changing the font values in Resource/styles/_fonts.styles?

Check out this commit: https://github.com/Elundris/Air-for-Steam/commit/d0bf35a9ab2e03620f8934cfdc82c5dfc922f5e4#commitcomment-12509769

Try removing "Regular" from the basefont and condensed font and let me know if that helps.

**Comment by SoundwaveL** [comment]
That fixed my issue, thanks for the assistance :)

**Comment by Elundris** [comment]
Seems that the newer versions of the Roboto font released with Material Design are referred to differently. Thanks for pointing this out, it shouldn't be an issue in the next release!
