### ISSUE TITLE
Family saftey breaks skin

### ISSUE THREAD

**Issue by zack6849** [Elundris/Air-for-Steam#73]
Please add the buttons for steam family safety, a fairly large number of people use it as another line of defense should their account get hacked, and your skin has no way to login and play my games if i have it enabled, as i cannot enter my pin to disable it.

Edit: going into big picture mode and entering my pin then exiting big picture works, however this is obviously not ideal.

**Comment by Elundris** [comment]
Answered in the FAQ: https://github.com/Elundris/Air-for-Steam/wiki#how-do-i-use-family-view-with-air

:)

**Comment by zack6849** [comment]
Jesus, that's really unobtrusive and hard to see, thank you for clarifying!
