### ISSUE TITLE
[Suggestion] Add "AirConfig" to hamburger menu

### ISSUE THREAD

**Issue by psydex** [Elundris/Air-for-Steam#75]
Add "AirConfig" to hamburger menu for easier access to Air's config file

**Comment by sebie** [comment]
Deffenitly a +1 to this, from me. I will try to find how other skins implemented this.

**Comment by CorruptComputer** [comment]
Hamburger menu?

**Comment by Elundris** [comment]
This *might* be possible (I'm actually not sure), but I'd rather keep the menu items "stock Steam" so to speak. Steam should still be Steam even if you are using Air, just prettier. :)
