### ISSUE TITLE
Pending notifications are not being displayed

### ISSUE THREAD

**Issue by psydex** [Elundris/Air-for-Steam#76]
![steamcommunity com](https://cloud.githubusercontent.com/assets/5594251/9355033/045d3a18-467e-11e5-901f-d9db4d5132f5.png)
(using latest version 18/08/15)

**Comment by sebie** [comment]
I am a little unsure of a 'pending' notification, however the flag is supposed to be white when you have unread notifications.

**Comment by psydex** [comment]
It should've shown a notification count beside it so I know how many unread notifications I have. 
A simple white flag won't make me notice I've unread notifications in any matter.

Is it possible to change it's color to green (for example) if there's unread notifications?

**Comment by sebie** [comment]
You will have to await @Elundris answer on that. I don't know if it is a sprite or if it just changes it's CSS color. 

Sorry about that.

**Comment by Elundris** [comment]
It's possible to change the color, you'll have to be able to edit .tga files though. This is the file you'll want to edit: \Steam\skins\Air-for-Steam\Graphics\onfocus\inbox_active.tga.

The icon does fade from white if you don't have any unread notifications, but if that's not obvious enough, I'd go the color changing route. Cheers!
