### ISSUE TITLE
Strange line in the middle of the page

### ISSUE THREAD

**Issue by benedictleejh** [Elundris/Air-for-Steam#77]
![screen shot](https://cloud.githubusercontent.com/assets/1317666/9547748/0350c4d4-4dcf-11e5-9012-0971077a4318.png)

I just installed this amazing skin on OS X, and noticed that there's a strange line in the lower middle that doesn't disappear no matter how i move or resize the client. You can see that grey line in the screen shot above.

Is this intended (seems unlikely)?

**Comment by Elundris** [comment]
If you sync up with the develop branch, that should fix the issue. Was a tiny part of the download notification background not disappearing properly. LMK if that doesn't fix it for ya!
