### ISSUE TITLE
New Beta Update contains new element

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [Elundris/Air-for-Steam#78]
A new element, designed to alert players about registering their mobile number, has been added to the Steam Client Beta today.

The menu button draws over this.

![Menu Button](https://i.gyazo.com/e4a8694105c83d0f661d73734a79ee59.png)

Currently using 2015-0818 on Windows 10.

**Comment by Elundris** [comment]
The phone bar should appear properly now, let me know if you guys see any more issues!
