### ISSUE TITLE
[Request] - Material Dark

### ISSUE THREAD

**Issue by TekFolf** [Elundris/Air-for-Steam#8]
If you've seen Google's Material Reference they now have two variants of their design.
One is Material light, the other is Material Dark, I'm wondering if you can create a dark variant of this skin.
Because I absolutely love this skin its just really harsh on the eyes I'm also a passionate lover of Dark GUI's.

**Comment by Elundris** [comment]
It's next on the to-do list and it will happen after the next set of changes I've got brewing. :)

**Comment by TekFolf** [comment]
Oh thank you so much, this is radical.
