### ISSUE TITLE
Monospace font on the Friends list (OSX)

### ISSUE THREAD

**Issue by kz-lt** [Elundris/Air-for-Steam#83]
I've installed Roboto, as the rest of the interface has Roboto, but the Friends list and the chat window are both using a monospace font instead. Know what's up?

Normal client:
![Normal](http://sgfc.co/n0aaP.png)

Friends list:
![Friends](http://sgfc.co/w3duV.png)

**Comment by kz-lt** [comment]
Also to add: Settings is also using a monospace font.
![Settings](http://sgfc.co/7glFOUR.png)

**Comment by kz-lt** [comment]
Solution found: You haven't included all the required fonts. Roboto Regular is required but it is not included. (Roboto = Roboto Regular on mac, maybe on other OS as well.)

**Comment by sebie** [comment]
If I understand correctly, to fix the issue you had to install a font **not** included in the [`+Extras`](https://github.com/Elundris/Air-for-Steam/tree/master/%2BExtras/Fonts) folder. Right?

**Comment by kz-lt** [comment]
My mistake, the Extra folder I was using was an old one. The current one should be correct.

**Comment by sebie** [comment]
Awesome, great to know that everything is working. Enjoy the skin!
