### ISSUE TITLE
Server Info dialog resize issues

### ISSUE THREAD

**Issue by The-MAZZTer** [Elundris/Air-for-Steam#84]
1. The player list does not vertically resize when resizing the window (for comparison, see how Team Fortress 2's in game one resizes).
2. If the "Auto Retry" pane is open (Attempt to join a full server to get it to appear), resizing the window down squishes the options. Only the Players list should be resize when the window is sized.

Using git revision bc77366.

**Comment by sebie** [comment]
Does this happen without the Air Skin in use? If so, this might be a Steam bug.

**Comment by The-MAZZTer** [comment]
Nope:

1. The player list resizes as expected.
2. The radio buttons appear below the push buttons. There is a different visual glitch caused by the dialog being able to be resized too small but it is different than the one I am seeing in Air.

**Comment by sebie** [comment]
Thanks, I hope this is enough for @Elundris to fix it.

Would you mind uploading a screenshot of this just in case?

**Comment by Elundris** [comment]
I'll look into this on my next bugfix pass, thanks for the report.

**Comment by The-MAZZTer** [comment]
Screenshots: http://imgur.com/a/5LRCj
