### ISSUE TITLE
Certain buttons missing

### ISSUE THREAD

**Issue by BraydenDean** [Elundris/Air-for-Steam#85]
Buttons missing throughout the Steam client, including missing play button, missing text in library, 
![screenshot from 2015-09-26 18-00-28](https://cloud.githubusercontent.com/assets/14267273/10120598/b418e55c-6478-11e5-85d3-77b3baa0d5d1.png)
![screenshot from 2015-09-26 18-01-38](https://cloud.githubusercontent.com/assets/14267273/10120599/b42a8d98-6478-11e5-822a-11a50eb0df15.png)
![screenshot from 2015-09-26 18-01-52](https://cloud.githubusercontent.com/assets/14267273/10120600/b43133aa-6478-11e5-9925-07ceab6433ff.png)

**Comment by BraydenDean** [comment]
I have installed all fonts and the issue persists

**Comment by Elundris** [comment]
That is extremely odd, can you try re-downloading Air and seeing if the text looks fine *before* you make any tweaks to the theme?

Also, what OS are you on?

**Comment by BraydenDean** [comment]
I am running Linux. My initial thought was that it was fonts, but I
installed all of them correctly. I will try redownloading it when I get
home.

**Comment by BraydenDean** [comment]
Redownloaded today and problem persists

**Comment by Elundris** [comment]
Sorry for the delay, I've been out of town.

Can you take a screenshot of what the details view looks like before making any tweaks? I'm having a hard time finding any consistency in which fonts appear and which don't. You are definitely winning the award for the oddest issue I've seen in awhile.

**Comment by BraydenDean** [comment]
![screenshot from 2015-10-13 16-00-33](https://cloud.githubusercontent.com/assets/14267273/10470620/9040f5ae-71c3-11e5-90bd-177f2fb016e2.png)

I already have changed all fonts, they all still load, and the sections that didn't load before still don't load. I changed everything back to defaults for this screenshot.

**Comment by Elundris** [comment]
Oh!

I think it's a color issue actually, there's something wrong with the focus colors. When you re-downloaded Air, did you fully remove your old installation first? Some of the color variables have been changed since the older versions so if you merged the new version over your old one it might have run into issues.

The default settings should load Air with the light theme enabled and the sky focus color. Let me know if that helps.

**Comment by BraydenDean** [comment]
I have a custom color scheme, I didn't even think of that being the
problem. I'll try changing it when I'm home

**Comment by BraydenDean** [comment]
Wow that was it. I can't believe I didn't think of that before. Enabling one of the other color styles fixed the issue.

**Comment by Elundris** [comment]
Woohoo, glad to hear it!
