### ISSUE TITLE
Navigational/Top Bar Button Display Issue

### ISSUE THREAD

**Issue by Imperial-Knight** [Elundris/Air-for-Steam#86]
With the recent update of the Steam client, the Air theme appears to have this odd button configuration.

![navbar-bad](https://cloud.githubusercontent.com/assets/14037442/10405339/71cbd0ca-6e95-11e5-824e-ff2d7e615683.png)

If this could be fixed that'd great.

Best regards,
Imperial Knight

**Comment by vdrandom** [comment]
It's the panel reminding you to enter your phone number. As a workaround you can just restart steam using the default skin, deal with the panel and then switch back to Air.

**Comment by Elundris** [comment]
This is fixed in the develop branch. I'm working on prepping an official release ASAP. Thanks!
