### ISSUE TITLE
Download Configurator?

### ISSUE THREAD

**Issue by JamesCoyle** [Elundris/Air-for-Steam#87]
Would it be possible to have an online configurator for the skin? It would be nice to be able to select which options to enable without having to do so manually every time there is an update. I personally prefer the dark theme with the friends button in the top right. I've used other features in the past too but it's too much hassle finding the files to update every time.

**Comment by sebie** [comment]
Something like [this](http://metroforsteam.com/settings/) for example? 

If so, it would be up to Inhibitor to upload it on the website.

**Comment by Elundris** [comment]
I don't have any specific plans to implement a web-based settings app at this point, but I'll keep my eye on it in case the opportunity presents itself.
