### ISSUE TITLE
GUI looks different on OSX

### ISSUE THREAD

**Issue by robos** [Elundris/Air-for-Steam#9]
![bildschirmfoto 2015-04-06 um 14 00 00](https://cloud.githubusercontent.com/assets/11066425/7004040/80f7c102-dc65-11e4-9822-843476105ef7.png)

Compared with the most recent screenshots, I assume this is not the way it is meant to look. Fonts are installed and it doesn't change between the developer and the master branch. Or did I miss something, I have to take care of on OS X?

**Comment by Elundris** [comment]
Ah, yeah... I was doing a little bit of work on the OSX version, but it still needs a lot more work. I'll hesitantly say that OSX is my next priority after a dark theme.

If you sync up with the develop branch as of just now, I right-aligned the window controls for now. They will do better over there for now until I can actually fully implement OSX styling.

**Comment by robos** [comment]
KK, good to know. Once you will do so, I'm glad to help with testing or whatever I can do. 

Got the latest version and they are back where they are meant to be. Though, in the Long term, they would make more sense on the left side, since all the Apps in OS X have it on the top left. Would be weird for steam to be they only exception. I'm eager to see, what your plans are, once your going for the full OS X implementation.

Keep up the good work and thanks.

**Comment by Elundris** [comment]
I totally agree. I moved them to the left with that goal in mind but then got distracted so it was only half implemented. Doesn't make much sense over there until it's fully styled and reogranized as needed.

**Comment by sebie** [comment]
Assuming that it is patched, which if I am not mistaken is -- Can we close this issue?

**Comment by Elundris** [comment]
Closing since this specific issue is resolved. Will still be working on the overarching OSX compatibility issues though, fear not.
