### ISSUE TITLE
UI bug + Fonts too big + Hidden games

### ISSUE THREAD

**Issue by Zekario** [Elundris/Air-for-Steam#90]
I like this skin, but there's a few problems I've been having.

The first is a weird UI bug. In the top-left corner, where it says "YOU", there is a hamburger menu as well as some green thing piled on top. [Here's a picture.](http://imgur.com/PKN5QCn)

Also, there doesn't appear to be a search bar and/or option to show hidden games. Are these hidden somewhere?

The fonts on menus are sometimes too big. The text on the buttons can sometimes be too big to display the hole thing, and does thi...
The options' text sometimes runs together, overlapping.

Thanks!

**Comment by sebie** [comment]
Hey,

That is Steam trying to get clients to get rigster their phone number, and this should be fixed (#78). Do you have the latest beta release?

There is a search bar when clicking on the 'Search' button next to your name on the top header. I guess if you wanted to view all you games, including the 'hidden ones' go to Library > Games?

Have you installed **all** the fonts in the `+Extras`?

Hope it helped.

**Comment by Zaukaj** [comment]
The update fixed the green thing, thanks.

I didn't notice the search bar, that answers that. When you right click a game and click 'Set Categories' you can check 'Hide this game in my library' and it won't show in your library list. I've been able to access them in a dropdown menu by clicking the word 'GAMES' on the search bar in the stock skin, but not with Air.

I re-copied the fonts provided, but it's still there. I don't suppose it's a major problem, just something I had noticed.

**Comment by sebie** [comment]
Hmm, I will try that myself when I get back home. And I will edit it based on my findings.

What is your screen size? Can you show me an example of it? From the screenshot doesn't show that occuring (only in the change categories, I think).

**Comment by Elundris** [comment]
@Zekario You can access hidden games by clicking on the little down-caret to the right of the Library menu item.

As for the font sizes, that might be due to the way Linux handles font rendering. I seem to recall that being an issue for others in the past. You can manually edit those in the \Air-for-Steam\Resource\styles\_fonts.styles file if you'd like.

Feel free to re-open this issue if you still need extra assistance. :)
