### ISSUE TITLE
Auto Update and Configurator

### ISSUE THREAD

**Issue by Seranok** [Elundris/Air-for-Steam#91]
Hey Elundris,
So you basically have the best skin on steam, and my opinion and experience have certainly been 5 stars. However I would love to see the following.
An Auto-Updater with a built in settings panel for changing themes, fonts, and what else. I would love to see that. Personally if you play TF2, you might know many HUDs(Custom UI For the game) uses auto-updaters with built in settings. Would love to see that.
and the next thing is not an issue but a how to.
I want to know how do you increase text size of the labels such as "Store, Library and others? If it isn't possible its fine, because I could adjust it to my eyes. 
Thanks a bunch for the skin and keep the updates coming.

**Comment by Elundris** [comment]
For your second question, open this file \Steam\skins\Air-for-Steam\Resource\styles\_fonts.styles in a text editor and do a search for "//Main Client".

You'll want to change CUINavButton, LibrarySearch, and FriendsSearch to your desired font size. Save and restart Steam.

A configurator is something that I don't have the time or resources to create. I do agree with you that it would be cool, but at this point it's already almost too much work just maintaining Air in it's current form.
