### ISSUE TITLE
Add Big Picture Mode button

### ISSUE THREAD

**Issue by laxu** [Elundris/Air-for-Steam#92]
With the Steam Controller out I unfortunately have to use Big Picture Mode to configure the controller so it would be nice to have a button for that in the top bar like on the default skin.

**Comment by Seranok** [comment]
+1

**Comment by Elundris** [comment]
You can access Big Picture from the main menu, is there any reason this does not work?

**Comment by laxu** [comment]
It works but is not fast and convenient like it is on the default skin.

**Comment by Elundris** [comment]
At this point, unless it becomes a blocking usability issue, I would rather keep the minimal aesthetic as much as possible.

**Comment by JamesCoyle** [comment]
Perhaps it could be optional like the friends button?
