### ISSUE TITLE
Minor Problems 

### ISSUE THREAD

**Issue by Seranok** [Elundris/Air-for-Steam#94]
@Elundris  So basically I opened today and I noticed the follow. I request you to first look at the following screenshots:
[This One](http://prntscr.com/8udkij) and [this one](http://prntscr.com/8udkxo)
1.If you noticed the scroll bar which you use it to move the page down is too small, nearly half the size of chrome and it isn't clearely aligned. However this is an annoying issue for me because I do not use a mouse which has scroll, instead I use the Mousepad. Moreover, if possible(pray gaben) if you can make the scrollbar assigned to color of the theme the person use(if possible)
2. How do you make the icons which you use to close, minimize Steam bigger. Thanks.

**Comment by Elundris** [comment]
1) If you are talking about the tiny scrollbar in the second screenshot (the counter strike picture), this is something that can't be changed by skins.
2) The icons are targa image files, you can find them in this folder: \Air-for-Steam\Graphics\onfocus\controls
