### ISSUE TITLE
Download Floating Action Button Issue

### ISSUE THREAD

**Issue by JamesCoyle** [Elundris/Air-for-Steam#95]
It would be nice if it was visible whenever downloads are available. Currently it is only shown when downloads are active so it is hidden if you pause them.

**Comment by Elundris** [comment]
This was by design, there were a lot of people confused when the old download notification didn't disappear after the download was complete. I'm thinking of this button as more of an active download notification.

**Comment by JamesCoyle** [comment]
I agree it should be hidden when there are no downloads (ie the downloads page is empty) but when I pause a download or downloads are scheduled it would be a useful button to access the downloads page to manage them. You could change the icon when a download is in progress to indicate that something is being downloaded.

**Comment by Elundris** [comment]
Sadly I don't have that much control over how the icons are displayed. I'm already stretching what skins can do. If you recall the download notifications on the bottom bar of vanilla steam, it's quite different.

I think this is the best of the options available at this point.

**Comment by JamesCoyle** [comment]
I figured that may be the case. I had a look at making my own at one point but it seemed too complicated and limited to bother spending time on. 

As a 'downloads active' button it really has limited use (only ever used if a download needs pausing). To me a 'downloads available' button makes much more sense logically as it acts as a notification that downloads are available, scheduled and/or ongoing allowing for quick access to start or stop them as required. If you disagree then fair enough but it would at least be nice to see as an option.

**Comment by Elundris** [comment]
I don't disagree personally, I'll see if I can easily make it an option.

**Comment by Elundris** [comment]
Ah darn, there was a specific bug that I was forgetting about that makes it impossible to do this style of a button any other way. :/

**Comment by JamesCoyle** [comment]
Ah damn, thanks anyway (for such a great skin mostly :P). Personally I think valve need to do an update of the interface and skinning to provide much more control over it. It would be nice if the friends/chat panel could be docked into the main steam window for example.
